# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'frontend.ui'
# Created by: PyQt5 UI code generator 5.15.4
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(945, 667)
        self.JARVIS = QtWidgets.QLabel(Form)
        self.JARVIS.setGeometry(QtCore.QRect(0, 0, 951, 711))
        self.JARVIS.setText("")
        self.JARVIS.setPixmap(QtGui.QPixmap("C:\\Users\\MANASI\\Desktop\\Jarvis\\GUI\\Black and blue wallpaper.jpg"))
        self.JARVIS.setScaledContents(True)
        self.JARVIS.setObjectName("JARVIS")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(370, 150, 351, 231))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\MANASI\\Desktop\\Jarvis\\GUI\\center gif.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(780, 10, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Bremen Bd BT")
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-image: url(:/newPrefix/neon-Green.jpg);\n"
                                      "color: rgb(194, 234, 182);\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 80, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bremen Bd BT")
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-image: url(:/newPrefix/video-frame-png-5.png);\n"
                                        "color: rgb(247, 223, 238);\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 210, 231, 61))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setStyleSheet("border-image: url(:/newPrefix/1st.jpg);\n"
                                       "color:white;\n"
                                       "font-size:20px;"
                                       )
        self.textBrowser.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 300, 231, 61))
        self.textBrowser_4.setAutoFillBackground(False)
        self.textBrowser_4.setStyleSheet("border-image: url(:/newPrefix/1st.jpg);\n"
                                         "color:white;\n"
                                         "font-size:20px;"
                                         )
        self.textBrowser_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_5.setGeometry(QtCore.QRect(20, 390, 231, 61))
        self.textBrowser_5.setAutoFillBackground(False)
        self.textBrowser_5.setStyleSheet("border-image: url(:/newPrefix/1st.jpg);\n"
                                         "color:white;\n"
                                         "font-size:20px;\n"
                                         "text-align:center;"
                                         )
        self.textBrowser_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 411, 81))
        self.label.setText("")
        self.label.setPixmap(
            QtGui.QPixmap("C:\\Users\\MANASI\\Desktop\\Jarvis\\GUI\\Jarvis Loading Screen gif.gif"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "RUN"))
        self.pushButton_2.setText(_translate("Form", "EXIT"))


import rec

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
